# Generated by Django 2.0.6 on 2018-07-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_auth_users', '0002_auto_20180703_1103'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='oauthproviders',
            table='oauth_providers',
        ),
        migrations.AlterModelTable(
            name='oauthusers',
            table='oauth_users',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='userresetpassword',
            table='user_reset_password',
        ),
        migrations.AlterModelTable(
            name='userverification',
            table='user_verification_code',
        ),
    ]
